### ISSUE TITLE
idea for codebase discoverability: sloppy spelling forgiveness/searching deeper into module hierarchy

### ISSUE THREAD

**Issue by alok** [hrsh7th/nvim-compe#318]
not sure if this is the right place for it, but what I wanted to know what you think of a "fuzzy full path/Module completion". Essentially autocompletion which goes 'through the dots'. Makes discovering related functions in a codebase much easier. some sort of fuzzy matching for short edit distances helps too.

**Comment by hrsh7th** [comment]
Do you know the editor/IDE that realize it?

**Comment by alok** [comment]
none, but i think vim's autocomplete is up to it.

# one possible design (not a good one probably)

say you need `a.b.c` and type `c` or `.c`. then it offers up anything that could work.

useless for short completions, but say you want `scipy.optimize.interp1d` in python.

then typing `int1d` should maybe offer it. could use type info to resolve completion?

**Comment by hrsh7th** [comment]
The `module/module-path` is a language-specific feature so compe can't support it generally.
It should be supported by LSP.

**Comment by tami5** [comment]
Yes, this sort of stuff is supported nowadays by lsp servers, since what we type get sent to it., However, you can always implement custom feature by contributing to the lsp server you use on a daily bases, perhaps come up with generic solution.

I think this is an awesome feature, like in rust if I can write `snn` instead of `services::Notify::new` it would so productive.
