### ISSUE TITLE
Feature Request: add an option to complete paths from the working directory

### ISSUE THREAD

**Issue by AdrienLeGuillou** [hrsh7th/nvim-compe#320]
when you trigger path completion, with "." or "/", it's either relative to the root folder ( / ) or the current file. 

Most of the time I open nvim at the root of my current project and all paths are defined relative to this. With R projects I will tipically edit a "R/test.R" file and if I want to source another file I'll do

```r
source("R/other.R")
```

it would be great to have the option to have `nvim-compe` complete this path from nvim working directory.

I see several possibilities for it:

- always trigger file completion for path in strings  (I had that with completion-nvim with:

```lua
g.completion_chain_complete_list = {
  default = {
    default = {
      { complete_items = {'lsp', 'snippets'} },
   },
   string = {
      { mode = 'file' },  -- use ins-complete "files" (search ins-compl in completion-nvim help)
    },
  },
}

```

- use a special trigger that would disappear after completion (e.g. "," triggers completion and after selection we get "R/other.R" without the trigger char

**Comment by srafi1** [comment]
Suggestion: a new prefix of `'.//'` that implements this feature by using vim's cwd instead of buf_dirname. If that sounds good, I can submit a PR for it.

**Comment by hrsh7th** [comment]
We should support `$HOME` notation and provide customization for it.

**Comment by srafi1** [comment]
@hrsh7th Assuming you mean defining a shortcut to either a path or function for evaluation to a path, wouldn't that be more under the scope of a snippet? For example, UltiSnips allows you to make a snippet like this:
```
snippet cwd
	`getcwd()`
```
completion-nvim and vim-vsnip likely have similar options, so I think expanding a snippet to a path and then utilizing nvim-compe's path completion makes more sense. Although, that may require a modification to the path completion logic so that text such as `R/` will trigger completion by looking at the contents of the `R` directory.

**Comment by hrsh7th** [comment]
At least,  if we support $HOME/$PWD, it would be useful.

Yes. snippets can use for this situation but shell variables more common way, I think.

**Comment by srafi1** [comment]
I submitted a pull request that implements this with support for all environment variables.

BTW, I also found a small bug while looking at the source code as described in #322 (this issue is also fixed in the PR).
