### ISSUE TITLE
Please support repeat "."

### ISSUE THREAD

**Issue by NickyTope** [hrsh7th/nvim-compe#349]
Absolutely love this plugin, the last thing I am missing from coc though is the ability to use the repeat action.

I believe the tpope/vim-repeat is designed to enable this for plugins but it is way over my know-how..

I use `cw` or `ciw` all the time and expect to be able to just hit "." to do the same change on future words, this breaks however if I use compe to complete the word (the repeat works but it only replaces with the text I entered before compe completion).

**Comment by otijhuis** [comment]
Was about to post the same issue. It seems like something recently broke though. I just tested it on my macbook and dot repeat worked with `cw` and `ciw` for instance. It still had issue with snippets with placeholders though. For instance `role="alert"` turned into `rolealert` when using repeat. 

On my work laptop it didn't work at all. Repeat just repeats the text you typed, not the final text that's inserted.

So I updated the plugins on my macbook. Now dot repeat no longer works.

**Comment by hrsh7th** [comment]
Please use issue template.

But Probably, I've understand the problem.

**Comment by otijhuis** [comment]
I'll add the template here to make sure it's clear.

#### Describe the bug

When using dot repeat (.) only the text that was typed before triggering the completion is repeated, not the full completed text that was inserted.

#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Type a word in a buffer, for example `import`
2. Go to the next line and type `im` to trigger the completion
3. Select `import` and complete it
4. Go to normal mode
5. Press dot (.) to repeat

#### Actual behavior

The text `im` will appear.

#### Expected behavior

The text `import` should appear.

#### Additional context (optional)

I think this used to work, at least partially. LSP snippets with placeholders didn't work (using vsnip).

Problem with snippets:
1. Open a html file with html language server
2. Add a role attribute to a tag by typing `ro` and selecting the `role~` LSP snippet completion
3. This will enter `role="_"` where the underscore is the cursor
4. Type `alert`. The text should say `role="alert"`
5. Go to normal mode
6. Press dot (.) to repeat

Instead of `role="target"` the text "roletarget" would appear.
