### ISSUE TITLE
Make sources from /after/plugin/ lazyloading

### ISSUE THREAD

**Issue by monkoose** [hrsh7th/nvim-compe#369]
#### Is your feature request related to a problem? Please describe.
Currently even so I don't use half of sources like `omni, treesitter` etc they are still loading on nvim startup. Could it be improved?
You can disable them with explicitly specify like `let g:loaded_compe_omni = 0`, but isn't it too verbose?

#### Describe the solution you'd like
Load them only on demand when you add them in your `source` option.

**Comment by ii14** [comment]
It's a duplicate of #220, which got closed by the bot. @hrsh7th suggested separating the sources into separate repos, but I think that just as you say, lazy loading is a better alternative and should be a pretty straightforward thing to do. I'll try to do it over the weekend, because it does improve startup time by a lot.
