### ISSUE TITLE
[Request] Suggest all words of currently open buffers

### ISSUE THREAD

**Issue by pidgeon777** [hrsh7th/nvim-compe#393]
With `coc.nvim` it is possible to suggest all the words in the currently open buffers.

How could we configure `nvim-compe`, to replicate the same behaviour?

**Comment by FinallyFinancialFreedom** [comment]
yes , i find https://github.com/nvim-lua/completion-nvim has a external source to support this, it's useful.

**Comment by pidgeon777** [comment]
We could take a cue from here:

https://github.com/steelsojka/completion-buffers

**Comment by pjcj** [comment]
See #147

**Comment by YodaEmbedding** [comment]
On a similar, less ambitious note, suggesting words that occur later on in the *same buffer* is very useful. Often times, I use a variable in the main body of the function, then go back up to include it as a parameter or define it in some way. But this variable does not get suggested because it does not exist yet!

**Comment by donkeyboy666** [comment]
I have noticed too, that in command mode `q`:  compe wont use words from the buffer you are currently editing, but the default completion does.
