### ISSUE TITLE
Function signature popup after completion

### ISSUE THREAD

**Issue by blami** [hrsh7th/nvim-compe#398]
#### Is your feature request related to a problem? Please describe.
This is more design decision question rather than feature request. Some other completion plugins also bundle popup that shows function signature even after completion ended (e.g. until you close brace or so). Is this on TODO list of compe or is it that compe only focuses on completion and signature popup after completion should be provided by other plugin?  

#### Describe the solution you'd like
I don't mind any of two solutions (part of compe or standalone plugin). Just would like to know if I should wait or look for other plugin that only provides signature.

#### Describe alternatives you've considered
I found https://github.com/ray-x/lsp_signature.nvim which seems to work fine. The only concern and reason I see for adding something similar to compe is that compe already talks to lsp so might avoid redundant queries (is it really concern?).

#### Additional context
N/A

It would be nice to mention in README.md that compe doesn't provide this functionality and that you should complement by other plugin if that is the direction (or put it on TODO list).

**Comment by hrsh7th** [comment]
Thank you.

Yes. I think the feature is out of scope because compe focuses to LSP's `completion` feature.

The LSP spec has a `textDocument/completion`, `completionItem/resolve` methods and `textDocument/signatureHelp` methods.
The last one is not relates to `completion`, I think.

And Your suggestion seems good because I'd ever received many many feature request for this.

**Comment by blami** [comment]
Yeah, makes perfect sense to me! I guess it will also make maintaining compe codebase clean and fast easier. Thanks for quick reply!
