### ISSUE TITLE
Change to per-buffer configuration

### ISSUE THREAD

**Issue by comfortablynick** [hrsh7th/nvim-compe#83]
I like the way this plugin works compared to completion-nvim, but it would be nice to be able to use it per buffer like most of the lsp-style plugins.

https://github.com/nvim-lua/completion-nvim/blob/fc9b2fd2d47bea6a8954de1b1b19f2330545b354/lua/completion.lua#L246-L265

This allows a lot of flexibility in how the plugin and associated autocmds are used. Currently, it looks like I'd have to do quite a bit of configuration just to prevent nvim-compe from triggering completion in places I don't want it (clap_input for example).

If nvim-compe provided an `on_attach` function, it could be used inside lsp `on_attach` or just a simple buffer autocmd. Is there any interest in this?

**Comment by ii14** [comment]
#84

**Comment by ii14** [comment]
I personally think it's better to do the deoplete approach, rather than what completion-nvim does. You provide the global config and then you can override the specific options for buffers.

It's easier to setup for users, it's trivial to implement in the current code base and you always have the option to make it act like `on_attach` function, by setting the global config to `{enabled = false}` and separately enabling it per buffer with desired options.

That's what's in my PR, although it assumes that the global config is defined at the moment, so it _might_ break if you don't call the `setup` function first. I'll be happy to further test it and fix the potential issues if that's the approach that @hrsh7th wants to take.

**Comment by hrsh7th** [comment]
I want you to explain to me `why is this feature needed?`.

I've happy your guys contribution but I'm the careful man to add new structure for code base.

**Comment by hrsh7th** [comment]
If the reason is this feature needed is `we want to stop auto-completation in specific buffer`, we should provide `let g:compe = { 'disabled' }` may be.

**Comment by ii14** [comment]
I explained it in my PR:

> The use case is primarily different sets of sources for different filetypes.
> 
> ```viml
> let s:compe_c = {}
> let s:compe_c.source = {
>   \ 'nvim_lsp': v:true,
>   \ }
> au FileType c,cpp call compe#setup_buffer(s:compe_c)
> ```
> 
> For example, one might want to use the [necosyntax](https://github.com/tamago324/compe-necosyntax) source by default, but disable it when a language server is attached.
> 
> ```lua
> local lspconfig = require 'lspconfig'
> local compe = require 'compe'
> 
> lspconfig.clangd.setup{
>   on_attach = function()
>     compe.setup_buffer({
>       source = {
>         nvim_lsp = true,
>       },
>     })
>   end,
> }
> ```

**Comment by comfortablynick** [comment]
> That's what's in my PR, although it assumes that the global config is defined at the moment, so it _might_ break if you don't call the `setup` function first. I'll be happy to further test it and fix the potential issues if that's the approach that @hrsh7th wants to take.

Ok, that makes sense. I didn't have the global config defined first. Thanks!

**Comment by hrsh7th** [comment]
Currrently, nvim-compe has a filetype configuration per source.

```viml
let g:compe = {}
let g:compe.source = {}
let g:compe.source.nvim_lsp = {
\   'filetypes': ['vim', 'javascript']
\ }
```

I understand the `compe#bufer_setup({})` is maximize flexibility but I'm worrying we really need it or not.

**Comment by ii14** [comment]
I think my example with `necosyntax` source is a good one. It's what I used to do when I was using `deoplete` plugin.

By default I had basic completion for every language from parsed syntax files (from necosyntax). But whenever a language server was attached, the necosyntax completion source was replaced with completion from LSP. Doing it that way, even if your language server breaks and doesn't want to start, you still have a basic completion without having to adjust your vimrc. If you add a new language server it will just automatically work too. It wouldn't be possible with just filetypes.

Other lua plugins follow a similar pattern of using `on_attach` functions too, so that could potentially mean better integration with other plugins.

I think it's worth to have this option. It doesn't really cost anything in maintenance or performance, as it's reusing the `Config` structure and just optionally storing it in a buffer variable. All we have to do is check if that variable exists in `Config.get()`, and that's the entire implementation.

**Comment by ii14** [comment]
> Doing it that way, even if your language server breaks and doesn't want to start, you still have a basic completion without having to adjust your vimrc.

It's also important to note, that language servers in neovim's LSP are often attached under certain conditions. They might require a `.git` directory, `tsconfig.json` or `package.json` file for JS/TS, `compile_commands.json` for C/C++, `go.mod` for Golang etc. It's not guaranteed that the language server will be attached based on the filetype.

**Comment by hrsh7th** [comment]
nvim-compe will detect `nvim-lsp` source via https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe_nvim_lsp/init.lua#L9

So you don't need to afraid nvim-lsp source is enabled even if the LSP is not running.

But necosyntax source situation is reasonable to me.

I will consider API.

**Comment by hrsh7th** [comment]
My desired API is `compe#setup({ ... }, bufnr)`/`require"compe".setup({}, bufnr)`.
What do you think about it? @ii14

**Comment by hrsh7th** [comment]
In this API design, if bufnr omitted, it represents `global configuration setup`.

**Comment by ii14** [comment]
That's a great idea. And if `bufnr == 0` then it's the current buffer, so it's consistent with the nvim api.

**Comment by hrsh7th** [comment]
The remaining consideration points are 

- the buffer specific configuration should be extended with global configuration or not?

**Comment by ii14** [comment]
Looking at the options we have right now, I think it makes more sense to inherit the values from the global config. Most people will probably prefer to keep the same options and just change the `source`.

**Comment by hrsh7th** [comment]
#84 has merged. Thank you @ii4!
